// 2. Define a class

// The part of the syntax before the opening curly brace is also referred to as the class header.
// Recommended naming conventions for naming a class:
//      - Don't use Kotlin keywords as a class name
//      - Use PascalCase for naming a class

// 6. Define a constructor

// The primary purpose of a constructor is to specify how the objects of the class are created.

// 6.1 Default constructor
// A default constructor is a constructor without parameters
// The Kotlin compiler auto-generates the default constructor

// 6.2 Define a parameterized constructor

// 7. Implement a relationship between classes
// In Kotlin, classes are final by default, which means they can't be extended. To make them extendable, you have to
// "open" them.
open class SmartDevice constructor(val name: String, val category: String) {
    // 5. Define a class properties

    // Properties are basically variables that are defined in the class body instead of the function body.
    // Immutable/read-only properties are defined with the val keyword, and mutable properties are defined with the
    // var keyword.
    var deviceStatus = "online"

    // 5.1 Getter and setter functions in properties

    // Kotlin properties use a backing field to hold a value in memory. A backing field is basically a class variable
    // defined internally in the properties. A backing field is scoped to a property, which means you can only access it
    // through the get() or set() property functions. It is autogenerated by the compiler and referenced with a field
    // identifier
//    var speakerVolume = 2
//        get() = field
//        set(value) {
//            field = value
//        }

    // Secondary construtor
    constructor(name: String, category: String, statusCode: Int): this(name, category) {
        deviceStatus = when(statusCode) {
            1 -> "online"
            0 -> "offline"
            else -> "unknown"
        }
    }

    // 4. Define a class methods
    
    // When you define a function in the class body, it's referred to as a member function or method, and it represents
    // the behavior of the class.
    fun turnOn() {
        println("Smart device is turned on.")
    }

    fun turnOff() {
        println("Smart device is turned off.")
    }
}

// 7.1 Create a subclass that extends the SmartDevice superclass
class SmartTvDevice(deviceName: String, deviceCategory: String):
    SmartDevice(name = deviceName, category = deviceCategory) {

    var speakerVolume = 2
        get() = field
        set(value) {
            if (value in 0..100) {
                field = value
            }
        }

    var channelNumber = 1
        set(value) {
            if (value in 0..200) {
                field = value
            }
        }

    fun increaseSpeakerVolume() {
        speakerVolume++
        println("Speaker volume increased to $speakerVolume")
    }

    fun nextChannel() {
        channelNumber++
        println("Next channel increased to $channelNumber")
    }
}

// 7.1.a Create the SmartLightDevice subclass of SmartDevice

class SmartLightDevice(deviceName: String, deviceCategory: String):
    SmartDevice(name = deviceName, category = deviceCategory) {


}

//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
fun main() {
    // 3. Create an instance of a class

    // val variables that contain an object reference are read-only themselves, but the objet proper they are
    // referencing remains mutable.
    // The following initializes a read-only variable smartTvDevice with an instance of the class SmartDevice.
    // 6.2 - If a class doesn't have a default constructor and you attempt to instantiate the object without arguments,
    // the compiler reports an error
//    val smartTvDevice = SmartDevice()
    val smartTvDevice = SmartDevice(name = "Android TV", category = "Entertainment")

    // 4.1 Call a method on an object

    // The call to a method in a class is similar to how you call other functions.
    // To call a method out of a class
    smartTvDevice.turnOn()
    smartTvDevice.turnOff()
}