// 2. Define a class

// The part of the syntax before the opening curly brace is also referred to as the class header.
// Recommended naming conventions for naming a class:
//      - Don't use Kotlin keywords as a class name
//      - Use PascalCase for naming a class

// 6. Define a constructor

// The primary purpose of a constructor is to specify how the objects of the class are created.

// 6.1 Default constructor
// A default constructor is a constructor without parameters
class SmartDevice {
    // 5. Define a class properties

    // Properties are basically variables that are defined in the class body instead of the function body.
    // Immutable/read-only properties are defined with the val keyword, and mutable properties are defined with the
    // var keyword.
    val name = "Android TV"
    val category = "Entertainment"
    val deviceStatus = "online"

    // 5.1 Getter and setter functions in properties

    // Kotlin properties use a backing field to hold a value in memory. A backing field is basically a class variable
    // defined internally in the properties. A backing field is scoped to a property, which means you can only access it
    // through the get() or set() property functions. It is autogenerated by the compiler and referenced with a field
    // identifier
    var speakerVolume = 2
        get() = field
        set(value) {
            field = value
        }

    // 4. Define a class methods
    
    // When you define a function in the class body, it's referred to as a member function or method, and it represents
    // the behavior of the class.
    fun turnOn() {
        println("Smart device is turned on.")
    }

    fun turnOff() {
        println("Smart device is turned off.")
    }
}

//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
fun main() {
    // 3. Create an instance of a class

    // val variables that contain an object reference are read-only themselves, but the objet proper they are
    // referencing remains mutable.
    // The following initializes a read-only variable smartTvDevice with an instance of the class SmartDevice.
    val smartTvDevice = SmartDevice()

    // 4.1 Call a method on an object

    // The call to a method in a class is similar to how you call other functions.
    // To call a method out of a class
    smartTvDevice.turnOn()
    smartTvDevice.turnOff()
}